version: '3'

services:
  reverse-proxy:
    image: nginx:1.15
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8080:80
    depends_on:
      - ui
      - backend

  ui:
    build: ./netlogo-trustmodel-ui/
    expose:
      - 80

  backend:
    build: ./netlogo-trustmodel-backend/
    expose:
      - 8080